### ISSUE TITLE
Datasety MFSR používajú neplatný typ

### ISSUE THREAD

**Issue by hornik-informo** [datova-kancelaria/nkod-pipeline#24]
Datasety (napr. https://data.gov.sk/set/35a8944fefea2d24fdbbf854392188d6) používajú hodnotu <https://data.gov.sk/def/dataset-type/2> pre dct:type.

Taká hodnota nie je v číselníku https://wiki.vicepremier.gov.sk/pages/viewpage.action?pageId=101817682

![image](https://github.com/datova-kancelaria/nkod-pipeline/assets/144911183/cac5097e-9ae1-465f-a2aa-e9812904fb7b)

**Comment by miroslavliska** [comment]
Áno vidím, prepošlem info do MFSR.

**Comment by miroslavliska** [comment]
Uzatváram toto issue. Je to už nahodené v issue, ktoré zoskkupuje viac vecí pre MFSR
https://github.com/datova-kancelaria/nkod-pipeline/issues/15#issuecomment-1938648992

**Comment by miroslavliska** [comment]
> ![image](https://private-user-images.githubusercontent.com/144911183/298393076-cac5097e-9ae1-465f-a2aa-e9812904fb7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjkxMjUsIm5iZiI6MTcwOTMyODgyNSwicGF0aCI6Ii8xNDQ5MTExODMvMjk4MzkzMDc2LWNhYzUwOTdlLTlhZTEtNDY1Zi1hMmFhLWU5ODEyOTA0ZmI3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQyMTMzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWQxYzYzMTIyYjlmZjQ5MzEwYmU2ZjA2MDk3NmUyYTNlZGVlYmNmZjhmMzg2YTFkM2I5Y2NmZjdjZjYzNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vs3AKaVoG9vDgk8nt2lxn9GLhY7J2DbJ9yfmYH0DBH4)
