### ISSUE TITLE
Duplicitný poskytovateľ MIRRI

### ISSUE THREAD

**Issue by hornik-informo** [datova-kancelaria/nkod-pipeline#30]
Poskytovateľ MIRRI http://data.gov.sk/id/legal-subject/50349287 sa vyskytuje v nahavestovaných dátach 2x, zrejme raz z data.gov.sk a raz z githubu pre LKOD - túto registráciu navrhujem odstrániť, aby sme zmigrovali len čisté dáta.

**Comment by miroslavliska** [comment]
> Poskytovateľ MIRRI http://data.gov.sk/id/legal-subject/50349287 sa vyskytuje v nahavestovaných dátach 2x, zrejme raz z data.gov.sk a raz z githubu pre LKOD - túto registráciu navrhujem odstrániť, aby sme zmigrovali len čisté dáta.

Priznam sa, ze presne nerozumiem tomuto problemu. Ved ked prejdeme na novy portal, tak data o poskytovateloch sa uz budu brat z uloziska (adresara) portalu a nie githubu. Alebo je problem v niecom inom?

**Comment by miroslavliska** [comment]
Aha, teraz som si všimol, že v zozname poskytovateľov je to 2x
p.@hornik-informo to je ale asi chyba na strane GUI, nie? Ved oba MIRRI maju rovnake URI (rovnaku identiftu)

![image](https://github.com/datova-kancelaria/nkod-pipeline/assets/37801000/e71f74b7-f885-4fc0-ab2d-42e1f673c89b)

**Comment by hornik-informo** [comment]
Už v SPARQL je MIRRI dvojmo. Skúsime to odfiltrovať v piatok pri importe.

![image](https://github.com/datova-kancelaria/nkod-pipeline/assets/144911183/a08445e6-5aea-4deb-a444-31f8ca963763)
