### ISSUE TITLE
Harvestácia LKODu Levoče - každý dataset má warning ohľadom licencie

### ISSUE THREAD

**Issue by martinarisk** [datova-kancelaria/nkod-pipeline#58]
Dobrý deň, chcel by som sa spýtať na datasety Levoče. Po novom sa objavilo upozornenie, že podmienky použitia nie sú vyplnené.

![image](https://github.com/datova-kancelaria/nkod-pipeline/assets/148961996/548dcc07-1e65-4b0b-a9cb-54e89d0f9a70)

Poprosil by som o informáciu, ktorý atribút v JSON-LD datasete nie je vyplnený. Tu je príklad aktuálneho JSON-LD, sekcia `"podmienky_použitia"`:
```
      "podmienky_použitia": {
        "typ": "Špecifikácia podmienok použitia",
        "autorské_dielo": "http://publications.europa.eu/resource/authority/licence/CC_BY_4_0",
        "autor": {
          "sk": "Levoča"
        },
        "databáza_chránená_zvláštnými_právami": "http://publications.europa.eu/resource/authority/licence/CC0",
        "databáza_ako_autorské_dielo": "http://publications.europa.eu/resource/authority/licence/CC_BY_4_0",
        "autor_databázy": {
          "sk": "Levoča"
        },
        "osobné_údaje": "https://data.gov.sk/def/personal-data-occurence-type/2"
      },
```

Pravdepodobne to súvisí s riešením našej otázky ohľadom licencie.

Ďakujem
Martin.

**Comment by lk8w** [comment]
Dobrý deň áno je to problém s licenciami. Odpovedal som k tomu tu: https://github.com/datova-kancelaria/nkod-pipeline/issues/50#issuecomment-2199822303

**Comment by lk8w** [comment]
Dobrý deň, problém bol odstránený, ospravedlňujeme sa že to dlhšie trvalo.
