### ISSUE TITLE
Harvestovanie geo vlastností

### ISSUE THREAD

**Issue by jozefhornik** [datova-kancelaria/nkod-pipeline#8]
Pri harvestovaní sú datasetom prideľované hodnoty https://data.gov.sk/def/XXX, ale číselník NUTS obsahuje hodnoty https://data.gov.sk/id/XXX.

![image](https://github.com/datova-kancelaria/nkod-sk/assets/66019378/c2cc5faf-4eea-41ec-9b04-bee4b6aa3891)

**Comment by miroslavliska** [comment]
Je to opravené:
![image](https://github.com/datova-kancelaria/nkod-pipeline/assets/37801000/b5fcfea4-bf6d-4ff2-8352-ebecc0437856)
